apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: kafka-server
spec: {}
status: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-kafka-server
  name: deploy-kafka-server
  namespace: kafka-server
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: deploy-kafka-server
  template:
    metadata:
      labels:
        app: deploy-kafka-server
    spec:
      containers:
        - image: javier644alfaro/server_kafka
          name: kafka-server-kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-kafka-server
  name: svc-kafka-server
  namespace: kafka-server
spec:
  type: LoadBalancer
  ports:
    - name: svc-kafka-server
      port: 3000
      protocol: TCP
  selector:
    app: deploy-kafka-server